export type IssueStatus = "Resolved" | "Open" | "Pending" | "Escalated" | "Closed";
export type RaisedBy = "Driver" | "Rider";

export interface Issue {
  id: string;
  date: string;
  raisedBy: RaisedBy;
  phone: string;
  issueType: string;
  vehicleType: string;
  plateNo: string;
  tripId: string;
  firstResponder: string;
  issueStatus: IssueStatus;
  escalatedTo: string;
  department: string;
  dueDate: string;
  agentData: string;
  source: string;
  comment: string;
}

export const ISSUES: Issue[] = [
  {
    id: "14355",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251911431616",
    issueType: "Trip Adjustment",
    vehicleType: "Basic",
    plateNo: "8EE190IF",
    tripId: "20E38F1",
    firstResponder: "Eyerus G.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Eyerus G.",
    source: "Call Center",
    comment: "Trip need to be adjusted cause the driver app was stuck in map info to atlas adjustment.",
  },
  {
    id: "14356",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251911963674",
    issueType: "Trip Adjustment",
    vehicleType: "Minibus",
    plateNo: "46FC77D4",
    tripId: "20E38F1",
    firstResponder: "Lidya K.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Lidya K.",
    source: "Portal",
    comment: "Trip need to be adjusted cause it has a fixed price it was a Minibus, it was from Bole to CMC.",
  },
  {
    id: "14357",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251911963674",
    issueType: "Trip Adjustment",
    vehicleType: "Minibus",
    plateNo: "DAE16714",
    tripId: "20E38F1",
    firstResponder: "Lidya K.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Lidya K.",
    source: "Portal",
    comment: "Trip need to be adjusted cause it has a fixed price it was a Minibus, it was from Bole to Megenagna.",
  },
  {
    id: "14358",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251964889994",
    issueType: "Trip Adjustment",
    vehicleType: "Minibus",
    plateNo: "34262E17",
    tripId: "20E38F1",
    firstResponder: "Lidya K.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Lidya K.",
    source: "Portal",
    comment: "Trip need to be adjusted cause it has a fixed price it was a Minibus, it was from Bole to Ayat.",
  },
  {
    id: "14359",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251964889994",
    issueType: "Trip Adjustment",
    vehicleType: "Minibus",
    plateNo: "B95D783A",
    tripId: "3F0A69F8",
    firstResponder: "Lidya K.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Lidya K.",
    source: "Portal",
    comment: "Trip need to be adjusted cause it has a fixed price it was a Minibus, it was from Bole to Gerji.",
  },
  {
    id: "14362",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251950140300",
    issueType: "Reset Password",
    vehicleType: "Basic",
    plateNo: "",
    tripId: "",
    firstResponder: "Eyerus G.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Eyerus G.",
    source: "Call Center",
    comment: "Driver requested password reset. Verified identity and reset via admin panel.",
  },
  {
    id: "14363",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251911883428",
    issueType: "Reset Password",
    vehicleType: "Basic",
    plateNo: "",
    tripId: "",
    firstResponder: "Eyerus G.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Eyerus G.",
    source: "Call Center",
    comment: "Driver forgot login credentials. OTP sent to registered phone number. Issue resolved.",
  },
  {
    id: "14364",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251930011630",
    issueType: "Driver Registration",
    vehicleType: "Basic",
    plateNo: "",
    tripId: "",
    firstResponder: "Eyerus G.",
    issueStatus: "Pending",
    escalatedTo: "Beka M.",
    department: "Supply",
    dueDate: "2026-04-15",
    agentData: "Eyerus G.",
    source: "Call Center",
    comment: "New driver applicant missing vehicle insurance document. Advised to submit within 5 business days.",
  },
  {
    id: "14365",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251911066817",
    issueType: "Driver Registration",
    vehicleType: "Basic",
    plateNo: "",
    tripId: "",
    firstResponder: "Eyerus G.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Eyerus G.",
    source: "Call Center",
    comment: "Driver license verification completed. Account activated successfully.",
  },
  {
    id: "14366",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251921372527",
    issueType: "Reset Password",
    vehicleType: "Basic",
    plateNo: "",
    tripId: "",
    firstResponder: "Kalkidan B.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Kalkidan B.",
    source: "Call Center",
    comment: "meshualekyia to arabsa — password reset completed after identity verification.",
  },
  {
    id: "14367",
    date: "2026-04-15",
    raisedBy: "Rider",
    phone: "251921480523",
    issueType: "Rider Request",
    vehicleType: "Economy",
    plateNo: "",
    tripId: "",
    firstResponder: "Kalkidan B.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Kalkidan B.",
    source: "Call Center",
    comment: "Rider requested account information update. Email and phone number updated successfully.",
  },
  {
    id: "14369",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251911699004",
    issueType: "End Code",
    vehicleType: "Basic",
    plateNo: "9548E858",
    tripId: "",
    firstResponder: "Eyerus G.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Eyerus G.",
    source: "Call Center",
    comment: "Driver unable to end trip code. Admin manually closed the trip from backend.",
  },
  {
    id: "14370",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251907254648",
    issueType: "Reset Password",
    vehicleType: "Basic",
    plateNo: "",
    tripId: "",
    firstResponder: "Kalkidan B.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Kalkidan B.",
    source: "Call Center",
    comment: "Password reset completed. Driver confirmed successful login after reset.",
  },
  {
    id: "14371",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251962161214",
    issueType: "Trip Adjustment",
    vehicleType: "Basic",
    plateNo: "83952963",
    tripId: "20E38F1",
    firstResponder: "Yoseph K.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Yoseph K.",
    source: "Call",
    comment: "Trip need to be adjusted cause at the moment the driver don't have an app so the fare was calculated manually.",
  },
  {
    id: "14372",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251962161214",
    issueType: "Trip Adjustment",
    vehicleType: "Basic",
    plateNo: "0EAE FA80",
    tripId: "20E38F1",
    firstResponder: "Yoseph K.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Yoseph K.",
    source: "Call",
    comment: "Trip need to be adjusted cause at the moment the driver don't have an app so the fare was calculated manually.",
  },
  {
    id: "14373",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251962161214",
    issueType: "Trip Adjustment",
    vehicleType: "Basic",
    plateNo: "0D4B3B69",
    tripId: "74B50AB7",
    firstResponder: "Yoseph K.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Yoseph K.",
    source: "Call",
    comment: "Trip need to be adjusted cause at the moment the driver don't have an app so the fare was calculated manually.",
  },
  {
    id: "14376",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251909335504",
    issueType: "End Code",
    vehicleType: "Basic",
    plateNo: "A15CA1E8",
    tripId: "",
    firstResponder: "Kalkidan B.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Kalkidan B.",
    source: "Call Center",
    comment: "Driver could not end trip. Trip manually closed by support agent from admin dashboard.",
  },
  {
    id: "14377",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251911444113",
    issueType: "End Code",
    vehicleType: "Basic",
    plateNo: "EB52462A",
    tripId: "",
    firstResponder: "Kalkidan B.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Kalkidan B.",
    source: "Call Center",
    comment: "End code issue resolved. Trip closed and fare confirmed with driver.",
  },
  {
    id: "14378",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251909782021",
    issueType: "Driver Registration",
    vehicleType: "Basic",
    plateNo: "",
    tripId: "",
    firstResponder: "Kalkidan B.",
    issueStatus: "Pending",
    escalatedTo: "Beka M.",
    department: "Supply",
    dueDate: "2026-04-15",
    agentData: "Kalkidan B.",
    source: "Call Center",
    comment: "Driver registration pending background check clearance from Ethiopian Federal Police.",
  },
  {
    id: "14380",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251962161214",
    issueType: "Trip Adjustment",
    vehicleType: "Basic",
    plateNo: "E2F04328",
    tripId: "4EC23F1F",
    firstResponder: "Yoseph K.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Yoseph K.",
    source: "Call",
    comment: "Trip need to be adjusted cause at the moment the driver don't have an app so the fare was calculated manually.",
  },
  {
    id: "14383",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251912740186",
    issueType: "Pending Authorization",
    vehicleType: "Basic",
    plateNo: "AC428929",
    tripId: "",
    firstResponder: "Kalkidan B.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Kalkidan B.",
    source: "Call Center",
    comment: "Driver authorization was pending due to document review. Approved after verification.",
  },
  {
    id: "14384",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251977144486",
    issueType: "Trip Adjustment",
    vehicleType: "Basic",
    plateNo: "F94B3A5A",
    tripId: "",
    firstResponder: "Yoseph K.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Yoseph K.",
    source: "Call",
    comment: "Trip need to be adjusted cause the driver was a Minibus and he took them from Bole to Megenagna.",
  },
  {
    id: "14385",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251977144486",
    issueType: "Trip Adjustment",
    vehicleType: "Minibus",
    plateNo: "100B3F06",
    tripId: "",
    firstResponder: "Yoseph K.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Yoseph K.",
    source: "Call",
    comment: "Trip need to be adjusted cause the driver was a Minibus and he took them from Bole to CMC.",
  },
  {
    id: "14386",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251977144486",
    issueType: "Trip Adjustment",
    vehicleType: "Minibus",
    plateNo: "F1ED03E5",
    tripId: "DE92C3F9",
    firstResponder: "Yoseph K.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Yoseph K.",
    source: "Call",
    comment: "Trip need to be adjusted cause the driver was a Minibus and he took them from Bole to Ayat.",
  },
  {
    id: "14387",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251977144486",
    issueType: "Trip Adjustment",
    vehicleType: "Minibus",
    plateNo: "100D3B8F",
    tripId: "",
    firstResponder: "Yoseph K.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Yoseph K.",
    source: "Call",
    comment: "Trip need to be adjusted cause the driver was a Minibus and he took them from Bole to Gerji.",
  },
  {
    id: "14388",
    date: "2026-04-15",
    raisedBy: "Driver",
    phone: "251977144486",
    issueType: "Trip Adjustment",
    vehicleType: "Minibus",
    plateNo: "F8BD84FF",
    tripId: "",
    firstResponder: "Yoseph K.",
    issueStatus: "Resolved",
    escalatedTo: "Lidya K.",
    department: "Customer Care",
    dueDate: "closed",
    agentData: "Yoseph K.",
    source: "Call",
    comment: "Trip need to be adjusted cause the driver was a Minibus and he took them from Bole to Kazanchis.",
  },
];

export const ISSUE_TYPES = [
  "All", "Trip Adjustment", "Reset Password", "Driver Registration",
  "End Code", "Rider Request", "Pending Authorization", "Payment Issue", "App Bug",
];
export const STATUSES: IssueStatus[] = ["Resolved", "Open", "Pending", "Escalated", "Closed"];
export const STATUS_FILTER = ["All", ...STATUSES];
export const VEHICLE_TYPES = ["Basic", "Comfort +", "Comfort", "Mini Bus", "Lady Bug", "Parcel", "Luxury"];
export const DEPARTMENTS = ["Customer Care", "Supply", "Technical", "Finance"];
export const SOURCES = ["Call Center", "Portal", "Call", "Telegram", "Walk-in"];
export const RAISED_BY: RaisedBy[] = ["Driver", "Rider"];
